default:
  stylesheets:    [/opSkinHOUOUPlugin/css/bootstrap.css,/opSkinHOUOUPlugin/css/main.css]
  javascripts:    [https://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js,/opSkinHOUOUPlugin/js/main.js,http://twitter.github.com/bootstrap/1.4.0/bootstrap-dropdown.js]
